# generates a file with the default values
# rustfmt --print-config default .rustfmt.tml

max_width = 80
hard_tabs = false
tab_spaces = 2
# newline_style = "Auto"
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
wrap_comments = true
comment_width = 80
format_code_in_doc_comments = false
doc_comment_code_block_width = 80
normalize_comments = false
