[workspace]

members = [
  "01.1_hello",
  "01.2_hello_cargo",
  "03.1_variables",
  "03.2_data_types",
  "03.3_functions",
  "03.4_comments",
  "03.5_control_flow",
  "04.1_ownership",
  "04.2_references",
  "04.3_slice_type",
  "05.1_structs",
  "05.2_rectangles",
  "05.3_methods",
]
